lib/phone_db_web/router.ex
defmodule PhoneDbWeb.Router do
  use PhoneDbWeb, :router
  import Phoenix.LiveDashboard.Router

  use Plugoid.RedirectURI,
    token_callback: &PhoneDbWeb.TokenCallback.callback/5

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PhoneDbWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  defmodule PlugoidConfig do
    def common do
      config = Application.get_env(:phone_db, :oidc)

      [
        issuer: config.discovery_document_uri,
        client_id: config.client_id,
        scope: String.split(config.scope, " "),
        client_config: PhoneDbWeb.ClientCallback
      ]
    end
  end

  defp phone_auth(conn, _opts) do
    auth = Application.get_env(:phone_db, :phone_auth)
    Plug.BasicAuth.basic_auth(conn, auth)
  end

  pipeline :auth do
    plug Replug,
      plug: {Plugoid, on_unauthenticated: :pass},
      opts: {PlugoidConfig, :common}
  end

  pipeline :ensure_auth do
    plug Replug,
      plug: {Plugoid, on_unauthenticated: :auth},
      opts: {PlugoidConfig, :common}
  end

  pipeline :ensure_admin do
    plug PhoneDbWeb.Plug.CheckAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :phone_auth
  end

  scope "/", PhoneDbWeb do
    get "/_health", HealthCheckController, :index
  end

  live_session :default, on_mount: PhoneDbWeb.InitAssigns do
    scope "/", PhoneDbWeb do
      pipe_through [:browser, :auth]

      get "/", PageController, :index
      post "/logout", PageController, :logout
    end

    scope "/", PhoneDbWeb do
      pipe_through [:browser, :ensure_auth]

      get "/login", PageController, :login
      live "/phone_calls", ListPhoneCallLive, :index
      resources "/contacts", ContactController, only: [:edit, :new, :create, :update]
      live "/contacts", ListContactLive, :index
      live "/contacts/:id", ShowContactLive, :index
      resources "/defaults", DefaultController
    end
  end

  scope "/", PhoneDbWeb do
    pipe_through [:browser, :auth, :ensure_admin]
    live_dashboard "/dashboard", metrics: PhoneDbWeb.Telemetry
  end

  scope "/api", PhoneDbWeb do
    pipe_through :api
    post "/incoming_call", ApiController, :incoming_call
  end
end

lib/phone_db_web/views/layout_view.ex
defmodule PhoneDbWeb.LayoutView do
  use PhoneDbWeb, :html

  @spec prepend_if(list :: list(), condition :: bool(), item :: any()) :: list()
  def prepend_if(list, condition, item) do
    if condition, do: [item | list], else: list
  end

  def link_class(active, item) do
    ["nav-link"]
    |> prepend_if(active == item, "active")
    |> Enum.join(" ")
  end
end

lib/phone_db_web/templates/layout/app.html.eex
<%= @inner_content %>

lib/phone_db_web/templates/layout/app.html.heex
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <.link navigate={~p"/"} class="navbar-brand">
        PhoneDb
    </.link>
    <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarsExampleDefault"
    aria-controls="navbarsExampleDefault"
    aria-expanded="false"
    aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
        <% user = PhoneDbWeb.Auth.current_user(@conn) %>
        <% active = assigns[:active] %>
        <%= if user != nil do %>
            <li class="nav-item">
                <.link navigate={~p"/contacts/"} class={link_class(active, "contacts")}>
                    Contacts
                </.link>
            </li>
            <li class="nav-item">
                <.link navigate={~p"/phone_calls/"} class={link_class(active, "phone_calls")}>
                    Calls
                </.link>
            </li>
            <li class="nav-item">
                <.link navigate={~p"/defaults/"} class={link_class(active, "defaults")}>
                    Defaults
                </.link>
            </li>
            <%= if PhoneDbWeb.Auth.user_is_admin?(user) do %>
                <li class="nav-item">
                    <.link navigate={~p"/dashboard/home"} class={link_class(active, "dashboard")}>
                        Dashboard
                    </.link>
                </li>
            <% end %>
            <li class="nav-item dropdown">
                <a
                class="nav-link dropdown-toggle"
                href="#"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >
                <%= user["name"] %>
                </a>
                <div class="dropdown-menu">
                <%= link "Logout", to: ~p"/logout", method: :post, class: "dropdown-item" %>
                </div>
            </li>
        <% else %>
            <li class="nav-item">
                <.link navigate={~p"/login"} class={link_class(active, "login")}>
                    Login
                </.link>
            </li>
        <% end %>
    </ul>
    </div>
</nav>

<main role="main" class="container">
    <%= for {flash_key, flash_message} <- @flash do %>
        <p class={"alert alert-#{flash_key}"}><%= flash_message %></p>
    <% end %>
    <%= @inner_content %>
</main>

lib/phone_db_web/templates/layout/live.html.heex
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <.link navigate={~p"/"} class="navbar-brand">
        PhoneDb
    </.link>
    <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarsExampleDefault"
    aria-controls="navbarsExampleDefault"
    aria-expanded="false"
    aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
        <% user = assigns[:current_user] %>
        <% active = assigns[:active] %>
        <%= if user != nil do %>
            <li class="nav-item">
                <.link navigate={~p"/contacts/"} class={link_class(active, "contacts")}>
                    Contacts
                </.link>
            </li>
            <li class="nav-item">
                <.link navigate={~p"/phone_calls/"} class={link_class(active, "phone_calls")}>
                    Calls
                </.link>
            </li>
            <li class="nav-item">
                <.link navigate={~p"/defaults/"} class={link_class(active, "defaults")}>
                    Defaults
                </.link>
            </li>
            <%= if PhoneDbWeb.Auth.user_is_admin?(user) do %>
                <li class="nav-item">
                    <.link navigate={~p"/dashboard/home"} class={link_class(active, "dashboard")}>
                        Dashboard
                    </.link>
                </li>
            <% end %>
            <li class="nav-item dropdown">
                <a
                class="nav-link dropdown-toggle"
                href="#"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >
                <%= user["name"] %>
                </a>
                <div class="dropdown-menu">
                <%= link "Logout", to: ~p"/logout", method: :post, class: "dropdown-item" %>
                </div>
            </li>
        <% else %>
            <li class="nav-item">
                <.link navigate={~p"/login"} class={link_class(active, "login")}>
                    Login
                </.link>
            </li>
        <% end %>
    </ul>
    </div>
</nav>

<main role="main" class="container">
    <%= for {flash_key, flash_message} <- @flash do %>
        <p class={"alert alert-#{flash_key}"} phx-click="lv:clear-flash">
            <%= flash_message %>
        </p>
    <% end %>
    <%= @inner_content %>
</main>

lib/phone_db_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PhoneDb</title>
    <link
      rel="stylesheet"
      href="<%= Routes.static_path(@conn, "/css/app.css") %>"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link("PhoneDb", to: Routes.page_path(@conn, :index), class: "navbar-brand") %>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <%= if PhoneDb.Auth.user_signed_in?(@conn) do %>
            <li class="nav-item">
              <%= link("Contacts", to: Routes.list_contact_path(@conn, :index), class: "nav-link " <> active_class(@active, "contacts")) %>
            </li>
            <li class="nav-item">
              <%= link("Calls", to: Routes.list_phone_call_path(@conn, :index), class: "nav-link " <> active_class(@active, "phone_calls")) %>
            </li>
            <li class="nav-item">
              <%= link("Defaults", to: Routes.default_path(@conn, :index), class: "nav-link " <> active_class(@active, "defaults")) %>
            </li>
            <%= if PhoneDb.Auth.user_is_admin?(@conn) do %>
              <li class="nav-item <%= active_class(@active, "users") %>">
                <%= link("Users", to: Routes.user_path(@conn, :index), class: "nav-link " <> active_class(@active, "users")) %>
              </li>
            <% end %>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <%= PhoneDb.Auth.current_user(@conn).username %>
              </a>
              <div class="dropdown-menu">
                <%= link "Logout", to: Routes.session_path(@conn, :logout), method: :post, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item <%= active_class(@active, "login") %>">
              <%= link("Login", to: Routes.session_path(@conn, :login), class: "nav-link " <> active_class(@active, "login") ) %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <%= for {flash_key, flash_message} <- get_flash(@conn) do %>
        <p class="alert alert-<%= flash_key %>"><%= flash_message %></p>
      <% end %>
      <%= @inner_content %>
    </main>

    <footer class="text-muted small">
      <div class="container">
        Version <%= Application.get_env(:phone_db, :vcs_ref) %> built on
        <%= Application.get_env(:phone_db, :build_date) %>
      </div>
    </footer>

    <%= csrf_meta_tag() %>
    <script
      type="text/javascript"
      src="<%= Routes.static_path(@conn, "/js/app.js") %>"
    ></script>
  </body>
</html>

lib/phone_db_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PhoneDb</title>
    <link
      rel="stylesheet"
      href={Routes.static_path(@conn, "/css/app.css")}
    />
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/js/app.js")}></script>
  </head>
  <body>
    <%= @inner_content %>
    <%= csrf_meta_tag() %>
    <footer class="text-muted small">
      <div class="container">
        Version <%= Application.get_env(:phone_db, :vcs_ref) %> built on
        <%= Application.get_env(:phone_db, :build_date) %>
      </div>
    </footer>
  </body>
</html>